# Generated by Django 4.2.3 on 2023-07-30 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_remove_socios_activo_remove_socios_apellidos_and_more'),
        ('ayudas_econ', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayudaseconomicas',
            name='socio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='socios.socios'),
        ),
    ]
