# Generated by Django 4.2.3 on 2023-07-30 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayudas_econ', '0002_alter_ayudaseconomicas_socio'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayudaseconomicas',
            name='valorsocio',
            field=models.DecimalField(decimal_places=2, default=3, max_digits=8),
            preserve_default=False,
        ),
    ]
