# Generated by Django 4.2.3 on 2023-09-16 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayudas_econ', '0004_consumoscuotaordinaria_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayudasexternas',
            name='pertenece_uteq',
            field=models.BooleanField(default=False),
        ),
    ]
