# Generated by Django 4.2.3 on 2023-07-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayudas_econ', '0004_detallesayuda'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallesayuda',
            name='fecha',
            field=models.DateTimeField(null=True),
        ),
    ]
