# Generated by Django 4.2.3 on 2023-09-16 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayudas_econ', '0005_ayudasexternas_pertenece_uteq'),
    ]

    operations = [
        migrations.AddField(
            model_name='ayudasexternas',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
