# Generated by Django 4.2.3 on 2023-08-15 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayudas_econ', '0006_alter_ayudaseconomicas_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallesayuda',
            name='fecha',
            field=models.DateField(null=True),
        ),
    ]
