# Generated by Django 4.2.3 on 2023-09-08 17:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ayudas_econ', '0007_alter_detallesayuda_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='AyudasExternas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField(max_length=200)),
                ('cedula', models.TextField(max_length=10)),
                ('fecha', models.DateField()),
                ('detalle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayudas_econ.detallesayuda')),
            ],
        ),
    ]
