# Generated by Django 4.2.4 on 2023-09-09 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ayudas_econ', '0009_ayudasexternas_valor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ayudasexternas',
            name='detalle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ayudas_econ.ayudaseconomicas'),
        ),
    ]
