# Generated by Django 4.2.4 on 2023-09-10 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayudas_econ', '0010_alter_ayudasexternas_detalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsumosCuotaOrdinaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField(max_length=300)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
