# Generated by Django 4.2.4 on 2023-09-10 12:51

import Prestamos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ayudas_econ', '0011_consumoscuotaordinaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumoscuotaordinaria',
            name='evidencia',
            field=models.FileField(blank=True, null=True, upload_to=Prestamos.models.upload_to_evidencia),
        ),
    ]
