# Generated by Django 4.2.4 on 2023-09-10 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ayudas_econ', '0008_detallesayuda_pagado'),
        ('ayudas_econ', '0012_consumoscuotaordinaria_evidencia'),
    ]

    operations = [
    ]
