# Generated by Django 4.2.2 on 2023-07-09 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socios', '0002_remove_socios_activo_remove_socios_apellidos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_prestamo', models.DateField(auto_now_add=True)),
                ('fecha_pago', models.DateField(null=True)),
                ('plazo_meses', models.PositiveIntegerField()),
                ('tasa_interes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descripcion', models.TextField(blank=True)),
                ('cancelado', models.BooleanField(default=True)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.socios')),
            ],
        ),
    ]
