# Generated by Django 4.2.3 on 2023-09-15 21:25

import Prestamos.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_total_ayuda_permanente_total_cuota_ordinaria_and_more'),
        ('Prestamos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='evidencia',
            field=models.FileField(blank=True, null=True, upload_to=Prestamos.models.upload_to_evidencia),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='fecha_primer_pago',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='tipo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='tasa_interes',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
        migrations.CreateModel(
            name='PagoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.PositiveIntegerField()),
                ('monto_pago', models.DecimalField(decimal_places=2, max_digits=8)),
                ('evidencia', models.FileField(blank=True, null=True, upload_to=Prestamos.models.upload_to_evidencia)),
                ('cancelado', models.BooleanField(default=False)),
                ('fecha_pago', models.DateField()),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prestamos.prestamo')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.socios')),
            ],
        ),
    ]
