# Generated by Django 4.2.3 on 2023-07-25 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_remove_socios_activo_remove_socios_apellidos_and_more'),
        ('Prestamos', '0002_alter_prestamo_cancelado'),
    ]

    operations = [
        migrations.CreateModel(
            name='PagoMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.PositiveIntegerField()),
                ('monto_pago', models.DecimalField(decimal_places=2, max_digits=8)),
                ('evidencia', models.FileField(blank=True, upload_to='')),
                ('fecha_pago', models.DateField()),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Prestamos.prestamo')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.socios')),
            ],
        ),
    ]
