# Generated by Django 4.2.3 on 2023-07-25 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0003_pagomensual'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagomensual',
            name='cancelado',
            field=models.BooleanField(default=False),
        ),
    ]
