# Generated by Django 4.2.3 on 2023-07-25 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0004_pagomensual_cancelado'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='total',
            field=models.DecimalField(decimal_places=2, default=100.0, max_digits=10),
            preserve_default=False,
        ),
    ]
