# Generated by Django 4.2.3 on 2023-09-08 13:52

import Prestamos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0006_alter_pagomensual_evidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='evidencia',
            field=models.FileField(blank=True, null=True, upload_to=Prestamos.models.upload_to_evidencia),
        ),
        migrations.AddField(
            model_name='prestamo',
            name='fecha_primer_pago',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
