# Generated by Django 4.2.4 on 2023-09-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Prestamos', '0008_prestamo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prestamo',
            name='tasa_interes',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
