# Generated by Django 4.2.3 on 2023-08-18 23:50

import Pagos.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0006_detallescupos_permanente'),
        ('socios', '0004_alter_aportaciones_socio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos_cuotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuotas', models.IntegerField()),
                ('cuota_actual', models.IntegerField()),
                ('consumo_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valor_cuota', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.BooleanField(default=False)),
                ('fecha_descuento', models.DateField()),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.socios')),
            ],
        ),
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_consumo', models.DateField()),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.socios')),
            ],
        ),
        migrations.CreateModel(
            name='Detalle_cuotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.IntegerField()),
                ('estado', models.BooleanField(default=False)),
                ('fecha_descuento', models.DateField()),
                ('evidencia', models.FileField(blank=True, null=True, upload_to=Pagos.models.upload_to_evidencia)),
                ('valor_cuota', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pago_cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pagos.pagos_cuotas')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.socios')),
            ],
        ),
    ]
