# Generated by Django 4.2.2 on 2023-07-05 15:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('socios', '0001_initial'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_consumo', models.DateTimeField()),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.socios')),
            ],
        ),
    ]
