<<<<<<< HEAD
# Generated by Django 4.2.4 on 2023-08-18 21:13
=======
# Generated by Django 4.2.3 on 2023-08-23 15:47
>>>>>>> e95f9740487bbf0c865ef80320e5c41a05b24e03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ('proveedores', '0006_detallescupos_permanente'),
        ('socios', '0004_alter_aportaciones_socio'),
=======
        ('socios', '0004_alter_aportaciones_socio'),
        ('proveedores', '0006_detallescupos_permanente'),
>>>>>>> e95f9740487bbf0c865ef80320e5c41a05b24e03
        ('Pagos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_cuotas',
            name='proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor'),
        ),
        migrations.AddField(
            model_name='detalle_cuotas',
            name='socio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='socios.socios'),
        ),
        migrations.AddField(
            model_name='detalle_cuotas',
            name='valor_cuota',
            field=models.DecimalField(decimal_places=2, default=120, max_digits=8),
        ),
        migrations.AddField(
            model_name='pagos',
            name='estado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='detalle_cuotas',
            name='valor_cuota',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
    ]
