# Generated by Django 4.2.3 on 2023-07-24 23:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_alter_proveedor_ruc'),
        ('socios', '0002_remove_socios_activo_remove_socios_apellidos_and_more'),
        ('Pagos', '0002_alter_pagos_fecha_consumo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pagos_cuotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuotas', models.IntegerField()),
                ('cuota_actual', models.IntegerField()),
                ('consumo_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valor_cuota', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.BooleanField(default=False)),
                ('fecha_descuento', models.DateField()),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.socios')),
            ],
        ),
    ]
