# Generated by Django 4.2.4 on 2023-08-26 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0002_detalle_cuotas_proveedor_detalle_cuotas_socio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_cuotas',
            name='valor_cuota',
            field=models.DecimalField(decimal_places=2, default=120, max_digits=8),
        ),
    ]
