# Generated by Django 4.2.3 on 2024-03-09 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0002_pagos_estado_alter_detalle_cuotas_proveedor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagos_cuotas',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
