# Generated by Django 4.2.3 on 2024-03-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0003_pagos_cuotas_descripcion'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalle_cuotas',
            options={'ordering': ['fecha_descuento']},
        ),
        migrations.AlterModelOptions(
            name='pagos',
            options={'ordering': ['fecha_consumo']},
        ),
        migrations.AlterModelOptions(
            name='pagos_cuotas',
            options={'ordering': ['fecha_descuento']},
        ),
        migrations.AddField(
            model_name='pagos_cuotas_pendientes',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='pagos_pendientes',
            name='descripcion',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
