# Generated by Django 4.2.3 on 2023-07-25 16:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0003_pagos_cuotas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_cuotas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.IntegerField()),
                ('estado', models.BooleanField(default=False)),
                ('fecha_descuento', models.DateField()),
                ('pago_cuota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pagos.pagos_cuotas')),
            ],
        ),
    ]
