# Generated by Django 4.2.3 on 2023-08-29 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0002_pagos_estado_alter_detalle_cuotas_proveedor_and_more'),
        ('Pagos', '0003_procedimientos_pagosProveedores'),
    ]

    operations = [
    ]
