# Generated by Django 4.2.3 on 2023-07-26 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0004_detalle_cuotas'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_cuotas',
            name='evidencia',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
