# Generated by Django 4.2.3 on 2023-09-09 16:31

import Pagos.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0006_alter_socios_options'),
        ('Pagos', '0004_merge_20230829_0356'),
    ]

    operations = [
        migrations.CreateModel(
            name='pagos_pendientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumo_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_consumo', models.DateField()),
                ('estado', models.BooleanField(default=False)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.socios')),
            ],
            options={
                'ordering': ['fecha_consumo'],
            },
        ),
        migrations.CreateModel(
            name='pagos_cuotas_pendientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuotas', models.IntegerField()),
                ('cuota_actual', models.IntegerField()),
                ('consumo_total', models.DecimalField(decimal_places=2, max_digits=8)),
                ('valor_cuota', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.BooleanField(default=False)),
                ('fecha_descuento', models.DateField()),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.socios')),
            ],
            options={
                'ordering': ['fecha_descuento'],
            },
        ),
        migrations.CreateModel(
            name='detalle_cuotas_pendientes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuota', models.IntegerField(default=0)),
                ('estado', models.BooleanField(default=False)),
                ('fecha_descuento', models.DateField()),
                ('evidencia', models.FileField(blank=True, null=True, upload_to=Pagos.models.upload_to_evidencia)),
                ('valor_cuota', models.DecimalField(decimal_places=2, max_digits=8)),
                ('pago_cuota_pendientes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Pagos.pagos_cuotas_pendientes')),
                ('socio', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='socios.socios')),
            ],
            options={
                'ordering': ['fecha_descuento'],
            },
        ),
    ]
