# Generated by Django 4.2.3 on 2023-07-26 06:33

import Pagos.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0005_detalle_cuotas_evidencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_cuotas',
            name='evidencia',
            field=models.FileField(blank=True, null=True, upload_to=Pagos.models.upload_to_evidencia),
        ),
    ]
