# Generated by Django 4.2.3 on 2023-09-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0005_pagos_pendientes_pagos_cuotas_pendientes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detalle_cuotas',
            name='valor_cuota',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
