# Generated by Django 4.2.3 on 2023-08-15 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0004_detallescupos'),
        ('socios', '0004_alter_aportaciones_socio'),
        ('Pagos', '0007_detalle_cuotas_valor_cuota'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_cuotas',
            name='proveedor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='detalle_cuotas',
            name='socio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='socios.socios'),
            preserve_default=False,
        ),
    ]
