# Generated by Django 4.2.3 on 2023-08-15 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0008_detalle_cuotas_proveedor_detalle_cuotas_socio'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalle_cuotas',
            name='valor_cuota1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
