# Generated by Django 4.2.3 on 2023-08-15 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pagos', '0009_detalle_cuotas_valor_cuota1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalle_cuotas',
            name='valor_cuota1',
        ),
    ]
