# Generated by Django 4.2.3 on 2023-08-16 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Periodo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
