# Generated by Django 4.2.3 on 2023-08-18 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Periodo', '0002_alter_periodo_nombre'),
    ]

    operations = [
        migrations.CreateModel(
            name='AjustesSistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('periodoAutomatico', models.BooleanField(default=True)),
            ],
        ),
    ]
