# Generated by Django 4.2.3 on 2023-09-03 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Periodo', '0003_ajustessistema'),
    ]

    operations = [
        migrations.AddField(
            model_name='ajustessistema',
            name='dia_cierre',
            field=models.CharField(default=15, max_length=2),
        ),
    ]
