# Generated by Django 4.2.3 on 2023-09-15 21:25

from django.db import migrations, models
import django.db.models.deletion
import promociones.models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_alter_proveedor_options_remove_proveedor_ruc_and_more'),
        ('promociones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promocion',
            name='evidencia',
            field=models.FileField(blank=True, null=True, upload_to=promociones.models.upload_to_evidencia),
        ),
        migrations.AddField(
            model_name='promocion',
            name='tipo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='promocion',
            name='proveedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor'),
        ),
    ]
