# Generated by Django 4.2.3 on 2023-07-30 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('socios', '0002_remove_socios_activo_remove_socios_apellidos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aportaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_aportacion', models.CharField(choices=[('AE', 'Ayuda Económica'), ('CO', 'Cuota Ordinaria')], max_length=2)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha', models.DateField(null=True)),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
