# Generated by Django 4.2.3 on 2023-09-16 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_total_ayuda_permanente_total_cuota_ordinaria_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socios',
            name='genero',
            field=models.CharField(default='Masculino', max_length=10),
            preserve_default=False,
        ),
    ]
