# Generated by Django 4.2.3 on 2023-09-09 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0005_alter_socios_fecha_nacimiento_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socios',
            options={'ordering': ['user__last_name']},
        ),
    ]
