# Generated by Django 4.2.4 on 2023-09-12 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0006_alter_socios_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Total_Ayuda_Permanente',
            fields=[
                ('tipo_aportacion', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('total_actual', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_transaccion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Total_Cuota_Ordinaria',
            fields=[
                ('tipo_aportacion', models.CharField(max_length=2, primary_key=True, serialize=False)),
                ('total_actual', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fecha_transaccion', models.DateField()),
            ],
        ),
    ]
