# Generated by Django 4.2.4 on 2023-09-10 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0006_alter_socios_options'),
        ('socios', '0006_total_ayuda_permanente_total_cuota_ordinaria'),
    ]

    operations = [
    ]
