# Generated by Django 4.2.3 on 2023-09-10 20:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0006_total_ayuda_permanente_total_cuota_ordinaria'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='socios',
            options={'ordering': ['user__last_name']},
        ),
    ]
