# Generated by Django 4.2.3 on 2023-09-10 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0006_alter_socios_options'),
        ('socios', '0007_total_ayuda_permanente_total_cuota_ordinaria'),
    ]

    operations = [
    ]
