# Generated by Django 4.2.3 on 2023-09-15 08:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0008_total_cuota_ordinaria_tipo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='total_cuota_ordinaria',
            name='tipo',
        ),
    ]
