# Generated by Django 4.2.2 on 2023-07-08 09:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(default='1250259114', max_length=10, unique=True)),
                ('nombres', models.CharField(default='Jose', max_length=100)),
                ('apellidos', models.CharField(default='Nuñez', max_length=100)),
                ('fecha_nacimiento', models.DateField(default='2001-03-13')),
                ('correo_electronico', models.EmailField(default='user@gmail.com', max_length=254, unique=True)),
                ('numero_telefonico', models.CharField(default='0960138819', max_length=20, unique=True)),
                ('direccion_domiciliaria', models.CharField(default='SANTO', max_length=100)),
                ('fecha_ingreso', models.DateField(default='2012-01-01')),
                ('titulo', models.CharField(default='Contadora', max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
