# Generated by Django 4.2.2 on 2023-06-25 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0003_alter_proveedor_ruc'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='done',
            field=models.BooleanField(default=False),
        ),
    ]
