# Generated by Django 4.2.2 on 2023-06-25 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0004_proveedor_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='done',
            new_name='estado',
        ),
    ]
