# Generated by Django 4.2.2 on 2023-06-26 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0005_rename_done_proveedor_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='RUC',
            field=models.TextField(),
        ),
    ]
