# Generated by Django 4.2.2 on 2023-06-26 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0006_alter_proveedor_ruc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='RUC',
            field=models.CharField(max_length=13),
        ),
    ]
