# Generated by Django 4.2.3 on 2023-09-06 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PagosProveedor', '0002_pagosproveedor_evidencia'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagosproveedor',
            name='comision',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='pagosproveedor',
            name='fecha_creacion',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pagosproveedor',
            name='valor_total',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
    ]
