# Generated by Django 4.2.2 on 2023-07-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('telefono', models.CharField(max_length=13)),
                ('RUC', models.CharField(max_length=13)),
                ('direccion', models.CharField(max_length=500)),
                ('comision', models.DecimalField(decimal_places=2, max_digits=8)),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
    ]
