# Generated by Django 4.2.3 on 2023-09-15 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_total_ayuda_permanente_total_cuota_ordinaria_and_more'),
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proveedor',
            options={'ordering': ['nombre']},
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='RUC',
        ),
        migrations.AddField(
            model_name='proveedor',
            name='cupo',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=8),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='comision',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='detallesCupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('permanente', models.BooleanField(default=True)),
                ('fechaccupo', models.DateField(null=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.socios')),
            ],
        ),
        migrations.CreateModel(
            name='CuentaBancaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banco', models.CharField(max_length=100)),
                ('numero_cuenta', models.CharField(max_length=50)),
                ('tipo_cuenta', models.CharField(max_length=50)),
                ('titular_cuenta', models.CharField(max_length=100)),
                ('cedulaORuc', models.CharField(max_length=100)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='ComisionHistorica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comision_anterior', models.IntegerField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
            ],
        ),
        migrations.AddField(
            model_name='proveedor',
            name='ruc',
            field=models.CharField(default=111, max_length=13, unique=True),
            preserve_default=False,
        ),
    ]
