# Generated by Django 4.2.3 on 2024-03-09 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0002_alter_proveedor_options_remove_proveedor_ruc_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detallescupos',
            options={'ordering': ['socio__user__last_name']},
        ),
    ]
