# Generated by Django 4.2.3 on 2023-07-30 17:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0002_remove_socios_activo_remove_socios_apellidos_and_more'),
        ('proveedores', '0003_proveedor_cupo_alter_proveedor_comision'),
    ]

    operations = [
        migrations.CreateModel(
            name='detallesCupos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cupo', models.DecimalField(decimal_places=2, max_digits=8)),
                ('fechaccupo', models.DateField(null=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.socios')),
            ],
        ),
    ]
