# Generated by Django 4.2.4 on 2023-08-13 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0005_cuentabancaria'),
    ]

    operations = [
        migrations.AddField(
            model_name='detallescupos',
            name='permanente',
            field=models.BooleanField(default=True),
        ),
    ]
