# Generated by Django 4.2.3 on 2023-08-29 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0006_detallescupos_permanente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='RUC',
            new_name='ruc',
        ),
    ]
