<<<<<<< HEAD
# Generated by Django 4.2.3 on 2023-08-29 22:43
=======
# Generated by Django 4.2.3 on 2023-08-29 17:09
>>>>>>> 465939fba9e710cdac8a06579c8177560ce63d83

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0006_detallescupos_permanente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='RUC',
            new_name='ruc',
        ),
    ]
