<<<<<<< HEAD
# Generated by Django 4.2.3 on 2023-08-29 17:09
=======
# Generated by Django 4.2.3 on 2023-08-29 22:43
>>>>>>> 5af577c9ff530997f8dc704e5b9fc43890e5049e

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0006_detallescupos_permanente'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proveedor',
            old_name='RUC',
            new_name='ruc',
        ),
    ]
