# Generated by Django 4.2.5 on 2023-09-12 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0008_alter_proveedor_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComisionHistorica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comision_anterior', models.IntegerField()),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='proveedores.proveedor')),
            ],
            options={
                'ordering': ['-fecha_registro'],
            },
        ),
    ]
