# Generated by Django 4.2.3 on 2023-09-14 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0009_comisionhistorica'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comisionhistorica',
            options={},
        ),
    ]
